app/models.py
from . import db
from flask_login import UserMixin
from app import login_manager
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
class User(UserMixin,db.Model):
    """
    Class I will use to create users
    """
    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key = True)
    full_name = db.Column(db.String)
    username = db.Column(db.String)
    email = db.Column(db.String)
    bio = db.Column(db.String)
    image = db.Column(db.String)
    posts = db.relationship("Post", backref = "user", lazy = "dynamic")
    user_pass = db.Column(db.String)

    def save_user(self):
        db.session.add(self)
        db.session.commit()
        
    @property
    def password(self):
        raise AttributeError("pluto1")

    @password.setter
    def password(self,password):
        self.user_pass = generate_password_hash(password)

    def verify_pass(self,password):
        return check_password_hash(self.user_pass, password)
    


class Post(db.Model):
    __tablename__ = "posts"
    id  = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    content = db.Column(db.String)
    time = db.Column(db.String)
    image = db.Column(db.String)
    comments = db.relationship("Comment",backref = "post", lazy = "dynamic")
    def get_post_comments(self):
        return Comment.query.filter_by(post_id = self.id)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String)
    title = db.Column(db.String)
    content = db.Column(db.String)
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id"))
    time = db.Column(db.String)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

class Subscriber(db.Model):
    __tablename__ = "subscribers"
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms import SubmitField, SelectField
from ..models import Status


class StatusForm(FlaskForm):
    status = SelectField(
        u"Status", choices=[(1, "Received"), (2, "Processing"), (3, "Rejected"), (4, "Resolved")]
    )
    
    submit = SubmitField("Submit")

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class AddPostForm(FlaskForm):
    title = StringField("Title", validators = [Required()])
    content = TextAreaField("Post", validators = [Required()])
    submit = SubmitField("Add Post")

class SubscribeForm(FlaskForm):
    email = StringField("Enter email", validators = [Required()])
    submit = SubmitField("Subscribe")

class AddComment(FlaskForm):
    name = StringField("Name", validators = [Required()])
    comment = TextAreaField("Comment", validators = [Required()])
    submit = SubmitField("Comment")
    
class EditBio(FlaskForm):
    bio = StringField("Bio")
    submit = SubmitField("Update")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()
bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()
mail = Mail()
photos = UploadSet('photos',IMAGES)

# photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    # create instance of Flask
    app = Flask(__name__)
    # add configurations
    app.config.from_object(config_options[config_name])
    # initialize extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint,url_prefix ='/admin')

    #config uploads
    configure_uploads(app,photos)
    
    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from . import views,forms,errors

app/admin/views.py
from app.models import Case, Status
from flask import render_template, redirect, url_for
from . import admin
from .forms import StatusForm
from .. import db


@admin.route("/cases")
def listCases():

    """
    View admin root page function that returns the admin page and its data
    """

    cases = Case.query.order_by(Case.category)

    return render_template("admin/cases.html", cases=cases)


@admin.route("case/<int:id>", methods=["GET", "POST"])
def updateStatus(id):
    # case = Case.query.get(id)
    case = Case.query.get(id)

    form = StatusForm()
    if form.validate_on_submit():
        case.status_id = form.status.data

        db.session.add(case)
        db.session.commit()
        return redirect(url_for('.listCases', id=case.id))

    return render_template("admin/updateStatus.html", case=case, form=form)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors,forms

app/main/views.py
import os
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from .forms import AddPostForm
from datetime import datetime
from .. import db,photos
from app.models import Case,User,Role,Status
from flask_login import login_required

# views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    cases = Case.query.order_by(Case.category)
    return render_template('index.html',cases=cases)

@main.route("/Add/case/",methods = ["GET","POST"])
@login_required
def case():
    form = AddPostForm()
    title = "Add Post"
    if form.validate_on_submit():
        category = form.category.data
        title = form.title.data
        description = form.description.data
        geolocation = form.geolocation.data
        status_id = 1

        if "photo" in request.files:
            pic = photos.save(request.files["photo"])
            file_path = f"photos/{pic}"
            image = file_path
        post = Case(category = category, title = title, description=description, geolocation=geolocation, image = image, status_id=status_id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for(".dashboard"))
        
        
    return render_template("add_incidences.html",form = form,title = title)

@main.route('/map/<string:place>',methods=['GET','POST'])
def map(place):

    return render_template('add_incidence.html',place=place)

@main.route('/dashboard')
def dashboard():

    '''
    View root page function that returns the dashboard page and its data
    '''
    cases = Case.query

    return render_template('dashboard.html', cases=cases)

@main.route("/post/<int:id>",methods = ["GET","POST"])
def post_page(id):
    post = Case.query.filter_by(id = id).first()
    
    return render_template("display.html", post = post)
 
@main.route("/delete/case/<id>")
def delete_case(id):
    case = Case.query.filter_by(id = id).first()
    case_id = case.id
    db.session.delete(case)
    db.session.commit()
    return redirect(url_for(".dashboard"))

@main.route('/status', methods=["GET", "POST"] )
def status():

    '''
    View root page function that returns the index page and its data
    '''
    state= request.form.get("state")
    new_status=Status(status=state)
    db.session.add(new_status)
    db.session.commit()

    return render_template("edit_incidences.html")

app/templates/add_incidences.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content%}
    <div class="container">
        <div class="jumbotron" style="background-color:black; color: brown;">
            <form class="form-group" method="post" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                {{form.category.label}}
                {{form.category(class = "form-control",style="margin-bottom: 10px;")}}
                {{form.title.label}}
                {{form.title(class = "form-control",style="margin-bottom: 10px;")}}
                {{form.description.label}}
                {{form.description(class = "form-control", style="margin-bottom: 15px;")}}
                {{form.geolocation.label}}
                {{form.geolocation(class = "form-control",style="margin-bottom: 10px;")}}
                <input type="file" name="photo" id="" class="form-control" style="margin-bottom:15px">
                {{form.submit(class = "btn btn-sm btn-danger")}}
            </form>
            <div class="mapouter" >
                <div class="gmap_canvas">
                    <iframe width="700" height="300" id="gmap_canvas" src="https://maps.google.com/maps?q=nairobi&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
            </div>
        </div>
    </div>
{% endblock%}

app/templates/admin_incidences.html
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/incident.css')}}">
{% endblock%}
{%block content%}
<div class="container">
    <div class="db-content table bg-thematic-dark">
        <table class="main-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Media</th>
                    <th>User</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tr>
                <td>1</td>
                <td>Bribing at Salgaa</td>
                <td>Red Flag</td>
                <td>A police woman was taking money from a matatu at Salgaa road block</td>
                <td>Great North RD, Nakuru</td>
                <td>draft</td>
                <td>-</td>
                <td>Nyururu</td>
                <td><i class="fas fa-trash"></i> <a href="./edit_incident.html"><i class="fas fa-edit"></i></a></i></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Countless pothole</td>
                <td>Intervention</td>
                <td>Countless potholes on Mwiki road causing a lot of traffic</td>
                <td>Mwiki, Kiambu</td>
                <td>Under Investigation</td>
                <td>No</td>
                <td>Amimo</td>
                <td><i class="fas fa-trash"></i> <a href="./edit_incident.html"><i class="fas fa-edit"></i></a></i></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Nepotism</td>
                <td>Red flag</td>
                <td>Bribing at Engineer Birth Registration center</td>
                <td>Engineer, Nyandarua</td>
                <td>Resolved</td>
                <td>Yes</td>
                <td>Sheila</td>
                <td><i class="fas fa-trash"></i> <a href="./edit_incident.html"><i class="fas fa-edit"></i></a></i></td>
            </tr>
            <tr>
                <td>4</td>
                <td>Fallen Bridge</td>
                <td>Intervention</td>
                <td>A fallen Bridge at Muhoroni cutting transport</td>
                <td>Muhoroni, Kisumu</td>
                <td>Rejected</td>
                <td>-</td>
                <td>Pretorious</td>
                <td><i class="fas fa-trash"></i> <a href="./edit_incident.html"><i class="fas fa-edit"></i></a></i></td>
            </tr>
        </table>
    </div>
</div>
{%endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>i-Repoter</title>
</head>
<body>
    {% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../static/css/index.css">
    {% endblock %}
   
    {% block content %}
        {%block navbar%}
        {% include 'navbar.html' %}
        {%endblock%}
    {% endblock %}  
</body>
</html>

app/templates/dashboard.html
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/incident.css')}}">
{% endblock%}
<style>
    td{
        color: white;
    }
</style>

{%block content%}
<div class="container">
    <div class="flex-container db-card-row">
        <div class="db-card">
            <h3 style="font-size: x-large;">Received</h3>
            <span style="font-size: x-large;">4</span>
        </div>
        <div class="db-card">
            <h3 style="font-size: x-large;">Under Investigation</h3>
            <span style="font-size: x-large;">1</span>
        </div>
        <div class="db-card">
            <h3 style="font-size: x-large;">Resolved</h3>
            <span style="font-size: x-large;">1</span>
        </div>
        <div class="db-card">
            <h3 style="font-size: x-large;">Rejected</h3>
            <span style="font-size: x-large;">0</span>
        </div>
    </div>
    <div class="db-content table bg-thematic-dark">
        <table class="main-table">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Title</th>
                    <th>Geolocation</th>
                    <th>Status</th>
                    <th>View Case</th>
                </tr>
            </thead>
            <tbody>
            {% for case in cases %}
            <tr>
                <p>
                <td style="color: white;">{{case.category}}</td>
                <td style="color: white;">{{case.title}}</td>
                <td style="color: white;">{{case.geolocation}}</td>
                <td style="color: white;">{{case.status}}</td>
                <td style="color: white;">
                    <a href="/post/{{case.id}}">
                        <button type="button" class="btn btn-primary">View</button>
                        </a> 
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{%endblock%}

app/templates/display.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}
{% block styles%}
{{super()}}
<link rel="stylesheet" href="../static/css/post.css">
{% endblock %}
{% block content%}
<div class="container">
    <div class="jumbotron">
        <div class="card" style="width: 80rem; margin-left: 10%;">
            <img src="{{url_for('static', filename=post.image)}}" class="card-img-top" alt="" height="380px" width="800px">
            <div class="card-body">
                <p class="card-text" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; text-align: center; color:brown"><strong>{{post.title}}</strong></p>
                <p class="card-text" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; text-align: center; "><strong>{{post.description}}</strong></p>
            </div>
            {% if current_user.is_authenticated and post.status_id == 1 %}
                    <a href="{{url_for('main.delete_case',id=post.id)}}" class="btn btn-danger">Delete</a>
            {% endif %} 
        </div>
    </div>
</div>
    

{% endblock%}

app/templates/edit_incidences.html
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/incident.css')}}">
{% endblock%}
{%block content%}
<body class="bg">
    <div class="incident">
        <div class="container ">
            <div class='incident-form-wrapper'>
                <div>
                </div>
                <form action="" method="POST"  enctype="multipart/form-data" class="incident-form">
                    <div class='form-group admin-status'>
                        <label for=incident_type>Status <span class='required'>*</span></label>
    
                        <input type="text" id="state" name="state" style="color: black; font-size: large;" required/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="form-button" style="color: black;">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{%endblock%}

app/templates/edit_incident.html
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/incident.css')}}">
{% endblock%}
{%block content%}
<body class="bg">
    <div class="incident">
        <div class="container ">
            <div class='incident-form-wrapper'>
                <div>
                    <h1>Create an Incident</h1>
                    <button class="tag">Draft</button>
                </div>
                <form action='./incidences.html' enctype="multipart/form-data" class="incident-form">
                    
                    <div class='form-group admin-status'>
                        <label for=incident_type>Status <span class='required'>*</span></label>
    
                        <select name="incident_type" >
                            <option value="draft">Recieved</option>
                            <option value="ui">Under Investigation</option>
                            <option value="rejected">Rejected</option>
                            <option value="resolved">Resolved</option>
                        </select>
                    </div>
                    <div class='form-group'>
                        <label for=incident_type>Type <span class='required'>*</span></label>
    
                        <select name="incident_type" disabled>
                            <option value="">Select</option>
                            <option value="red_flag">Red Flag</option>
                            <option value="intervention">Intervention</option>
                        </select>
                    </div>
    
                    <div class="form-group">
                        <label for="title">Title <span class='required'>*</span></label>
                        <!-- <br> -->
                        <input type="text" name="title" placeholder="2-5 word description" disabled>
                    </div>
    
                    <div class="form-group">
                        <label for="description">Description <span class='required'>*</span></label>
                        <!-- <br> -->
                        <textarea name="description" placeholder="An explanation in detail of what you are reporting" disabled></textarea>
                    </div>
                    <div class="form-group">
                        <label for="media">Media</label>
                        <input type="file" name="media" accept="video/*,image/*" multiple disabled>
                        <br>
                        <span class="form-group-footer">Attach images and videos(You can select more that one file.)</span>
                    </div>
                    <div class="form-group">
                        <label for="location">Location</label>
                        <!-- <input type="textarea" name="location" placeholder="location"> -->
                        <div class="mapouter" >
                            <div class="gmap_canvas">
                                <iframe width="700" height="300" id="gmap_canvas" src="https://maps.google.com/maps?q=university%20of%20san%20francisco&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                    frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                        </div>
                    </div>
    
                    <div class="form-group">
                        <button type="submit" class="form-button">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
{%endblock%}

app/templates/four0wfour.html
{% extends 'base.html'%}

{% block content %}
<img src="https://kfg6bckb.media.zestyio.com/yalantis-interactive-404.gif" alt="">
{% endblock %}

app/templates/geo.html
{% extends "material/base.html" %}
{% block content %}

<!--Import Google Icon Font-->
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
 <!-- SHOWCASE -->
 <br>
    <div class="showcase container">
        <div class="row blue">
            <div class="col s12 m10 offset-m1 center">
                <h5>Welcome iReporter</h5>
                    <p>Report any act of corruption</p>
                <br>
            </div>
        </div>
    </div>
    <button>Loc</button>
    <div class="container">
        <div class="row">
            <div class="col s12 m12">
                <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                        <!-- Inserted Dynamic Places In Image -->
                        <img src="https://earth.google.com/web/search/{{place}}/" alt="map of {{place}}">
                    </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">World Map<i class="material-icons right">more_vert</i></span>
                            <p><a href="#">This is a {{place}}</a></p>
                        </div>
                        <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">Street Map<i class="material-icons right">close</i></span>
                            <div class="card-image waves-effect waves-block waves-light">
                                <!-- Inserted Dynamic Places In Image -->
                                <img class="activator" src="https://maps.googleapis.com/maps/api/streetview?size=700x300&location={{place}}" alt="street view of {{place}}">
                            </div>

                    </div>
                </div>	
            </div>
        </div>
    </div>

{% endblock %}

app/templates/incidences.html
{% extends 'base.html'%}
{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/incident.css')}}">
{% endblock%}
{%block content%}
<div class="container">
    <div class="flex-container add-button">
        <a href="{{url_for('main.index')}}">
            <button class="form-button">Add an Incident</button>
        </a>
    </div>
    <div class="db-content table bg-thematic-dark">
        <table class="main-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Media</th>
                </tr>
            </thead>
            <tr>
                <td>1</td>
                <td>Bribing at Salgaa</td>
                <td>Red Flag</td>
                <td>A police woman was taking money from a matatu at Salgaa road block</td>
                <td>Great North RD, Nakuru</td>
                <td>draft</td>
                <td>-</td>
                <td><i class="fas fa-trash"></i></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Countless pothole</td>
                <td>Intervention</td>
                <td>Countless potholes on Mwiki road causing a lot of traffic</td>
                <td>Mwiki, Kiambu</td>
                <td>Under Investigation</td>
                <td>True</td>
                <td><i class="fas fa-trash"></i></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Nepotism</td>
                <td>Red flag</td>
                <td>Bribing at Engineer Birth Registration center</td>
                <td>Engineer, Nyandarua</td>
                <td>Resolved</td>
                <td>True</td>
                <td><i class="fas fa-trash"></i></td>
            </tr>
            <tr>
                <td>4</td>
                <td>Fallen Bridge</td>
                <td>Intervention</td>
                <td>A fallen Bridge at Muhoroni cutting transport</td>
                <td>Muhoroni, Kisumu</td>
                <td>Rejected</td>
                <td>True</td>
                <td><i class="fas fa-trash"></i></td>
            </tr>
        </table>
    </div>
</div>
{% endblock%}

app/templates/macros.html
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.pitch_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<style>
  li{
    font-size: 15px;
  }
</style>
<body>
  <nav class="navbar navbar-light" style="background-color: rgb(34, 32, 32)">
      <div role="navigation">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                  <!-- <a class="navbar-brand" style="color: cornsilk;" href="/"><strong>i-ReporterApp</strong></a> -->
              </div>
              <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav" style="display: inline;">
                      <li><a style="color: brown; padding-left: 30px;" href="/">Home</a></li>
                      <li><a style="color: brown; padding-left:30px;" href="/dashboard">Dashboard</a></li>
                      
                      
                      <li><a style="color: brown; padding-left:30px;" href="{{url_for('main.case')}}">Report</a></li>
                      <li><a style="color: brown; padding-left:30px;" href="/admin/cases">Admin</a></li>
                      {% if current_user.is_authenticated%}
                      <li><a style="color: brown; padding-left: 30px;" href="{{url_for('auth.logout')}}">Sign Out</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right" style="display: inline;">
                    {% else %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" style="color: brown; padding-left: 30px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sign Up
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('auth.register')}}" style="color: brown;">Admin</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{url_for('auth.register')}}" style="color: brown;">User</a>
                          </div>
                      </li>
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" style="color: brown; padding-left: 30px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sign In
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('auth.login')}}" style="color: brown;">Admin</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{url_for('auth.login')}}" style="color: brown;">User</a>
                          </div>
                      </li>
                      
                    {% endif %}   
                  </ul>
              </div>
          </div>
      </div>    
  </nav> 
</body>